-   type: modbus.slavemap
    channel: *main_server
    slaveid: 0
    childs:
    -   type: modbus.registers
        mode: registers
        devs: [ REx6, DI1, DI2, DI3, DI4, DI5, DI6 ]
    -   type: modbus.registers
        mode: coils
        devs: [ REx6, DI1, DI2, DI3, DI4, DI5, DI6 ]


-   name: GPIODI
    type: gpiod.gpionotify
    chip_path: /run/unipi-plc/by-sys/DI/gpiochip
    #chip_path: /dev/gpiochip0
    childs:
        - { name: DI1,  type: gpiod.input, pin: 4,  input: 8,  register: 0, reg_bit: 0,  debounce_reg: 1010, counter_reg: 7, debounce: 0 }
        - { name: DI2,  type: gpiod.input, pin: 17, input: 9,  register: 0, reg_bit: 1,  debounce_reg: 1011, counter_reg: 9, debounce: 0  }
        - { name: DI3,  type: gpiod.input, pin: 27, input: 10, register: 0, reg_bit: 2,  debounce_reg: 1012, counter_reg: 11, debounce: 0 }
        - { name: DI4,  type: gpiod.input, pin: 23, input: 11, register: 0, reg_bit: 3,  debounce_reg: 1013, counter_reg: 13, debounce: 0 }
        - { name: DI5,  type: gpiod.input, pin: 22, input: 12, register: 0, reg_bit: 4,  debounce_reg: 1014, counter_reg: 15, debounce: 0 }
        - { name: DI6,  type: gpiod.input, pin: 24, input: 13, register: 0, reg_bit: 5,  debounce_reg: 1015, counter_reg: 17, debounce: 0 }

-   name: GPIORO
    type: gpiod.gpiochip
    chip_path: /run/unipi-plc/by-sys/RO/gpiochip
    childs:
        -   name: REx6
            type: gpiod.regcoils
            start_coil: 0
            register: 1
            pins: [ 7, 6, 5, 4, 3, 2 ]

