-   type: modbus.slavemap
    channel: *main_server
    slaveid: 7
    childs:
    -   type: modbus.registers
        mode: registers
        devs: [ RO_EMO_7 ]
    -   type: modbus.registers
        mode: coils
        devs: [ RO_EMO_7 ]


-   name: GPIORO_EMO7
    type: gpiod.gpiochip
    chip_path: /run/unipi-plc/by-sys/RO_EMO7/gpiochip
    childs:
        -   name: RO_EMO_7
            type: gpiod.regcoils
            start_coil: 0
            register: 1
            pins: [ 7, 6, 5, 4, 3, 2, 1, 0 ]


